version: '3'

services:
  db:
    image: postgres
  web:
    build: 
      context: .
      dockerfile: "Dockerfile"
    volumes:
      - ../site:/kmanga
    ports:
      - "8000:8000"
    depends_on:
      - db
