version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    environment :
      POSTGRES_PASSWORD: 'postgres'
      PGDATA: "/var/lib/postgresql/data/pgdata"

    ports:
      - "5432:5432"
    volumes:
      - ../pgdata:/var/lib/postgresql/data/pgdata
      - ../docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    environment:
      POSTGRES_DB: 'kmanga'
      POSTGRES_USER: 'kmanga'
      POSTGRES_PASSWORD: ''
      POSTGRES_HOST: 'db'


  web:
    image: kmanga-web
    build:
      context: .
      dockerfile: "Dockerfile"

    entrypoint: "/entrypoint.sh"
    command: ["python", "/site/kmanga/manage.py", "runserver", "0.0.0.0:8000"]

    volumes:
      - ../site:/site
      - ../media:/media
    ports:
      - "8000:8000"
    depends_on:
      - db


  scrapy:
    image: kmanga-web
    volumes:
      - ../site:/site
      - ../media:/media
    command: ["tail","-f","/dev/null"]
    environment:
      PYTHONPATH: /site:/site/kmanga:/site/scraper
      SCRAPY_SETTINGS_MODULE: scraper.settings


    depends_on:
      - web
      - db
